mode: chatops
gitSafeReplacementChar: "-"
branchName: "${issue.number}-${issue.title,}"
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feature/${sender.login}/
  - label: bug
    prefix: bugfix/${sender.login}/
