version: "3.4"

services:
  backend:
    build:
      context: ./backend/src
      dockerfile: ./Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ./backend/src/dev.env

  frontend:
    ports:
      - "3000:3000"
