# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

RUN dotnet tool install --global dotnet-ef
RUN dotnet tool install -g dotnet-aspnet-codegenerator
ENV PATH="${PATH}:/root/.dotnet/tools"

# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore


ENTRYPOINT [ "dotnet", "watch", "run", "-r", "linux-x64", "--launch-profile", "StoreBackend"]